# Stage 1: Build Angular app (client + server)
FROM node:20-bullseye AS build

WORKDIR /app

# Installer dépendances système pour build
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Copier package.json pour caching
COPY package*.json ./

# Installer dépendances
RUN npm install --legacy-peer-deps
RUN npm install rxjs --legacy-peer-deps
RUN npm install -g @angular/cli@latest

# Copier le reste du code
COPY . .

# Augmenter mémoire Node pour éviter crash build
ENV NODE_OPTIONS=--max_old_space_size=4096

# Build Angular app (client + server)
RUN ng build --configuration=production
RUN ng run projet_pfe_nawress_jebali:server:production

# Stage 2: Run Angular Universal server
FROM node:20-bullseye

WORKDIR /app

# Copier les builds client + server depuis l'étape précédente
COPY --from=build /app/dist/projet_pfe_nawress_jebali /app/dist/projet_pfe_nawress_jebali
COPY package*.json ./

# Installer uniquement les dépendances nécessaires pour production
RUN npm install --legacy-peer-deps --omit=dev

# Exposer le port Node
EXPOSE 4000

# Lancer le serveur Angular Universal


# Run Express SSR server
CMD ["node", "src/server.js"]
