# Use official Python slim image
FROM python:3.9-slim-bookworm

# Set working directory
WORKDIR /app

# Copy only the Backend folder
COPY Backend/ ./Backend

# Install system dependencies for OpenCV
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir flask flask-cors gunicorn requests opencv-python

# Expose Flask port
EXPOSE 3000

# Move into Backend
WORKDIR /app/Backend

# Run with Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:3000", "app:app"]

