# Stage 1: Build Angular app
FROM node:20-bullseye AS build

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Install RxJS
RUN npm install rxjs --legacy-peer-deps

# Install Angular CLI
RUN npm install -g @angular/cli@19.2.4

# Copy source code
COPY . .

# Avoid memory issues
ENV NODE_OPTIONS=--max_old_space_size=4096

# Build Angular app
RUN ng build projet_pfe_nawress_jebali --configuration production

# Stage 2: Serve the Angular app with Nginx
FROM nginx:alpine

# Copy built app
COPY --from=build /app/dist/projet_pfe_nawress_jebali /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
